name: galleryimage
description: Flutter plugin that list of images from URLs allows you to display and zoomable multi image on iOS and Android.
version: 1.0.2
homepage: https://github.com/BeshoyMelika/flutter-gallery-package

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_view: ^0.14.0
  cached_network_image: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
